# Generated by Django 2.2.3 on 2019-07-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('ELC', 'Electronics'), ('CA', 'Cars'), ('LA', 'Lands')], max_length=3)),
                ('description', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='')),
                ('price', models.IntegerField(max_length=12)),
                ('location', models.CharField(choices=[('RUH', 'Riyadh'), ('MAK', 'Makkah'), ('JED', 'Jeddah')], max_length=3)),
                ('mobile', models.IntegerField(max_length=10)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
