# Generated by Django 2.2.3 on 2019-07-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haraj_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to='items_pics'),
        ),
    ]
