# Generated by Django 2.2.3 on 2019-07-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haraj_App', '0002_auto_20190726_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=1600),
        ),
    ]
