# Generated by Django 2.2.3 on 2019-07-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haraj_App', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
